name: Build Packages and Test
on:
  push:
    branches:
      - main
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-and-build:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Print info
        run: |
          echo github.ref_type is ${{ github.ref_type }}
          echo github.event_name is ${{ github.event_name }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Setup Poetry
        uses: Gr1N/setup-poetry@v8
      - name: Install package
        run: poetry install --with=dev
      - name: Install Qt
        # See https://github.com/cbrnr/mnelab/issues/327#issuecomment-1074853392
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libxcb-icccm4 libxcb-image0 libxcb-keysyms1 \
            libxkbcommon-x11-0 xvfb libxcb-randr0 \
            libxcb-render-util0 libxcb-xinerama0 libegl1
      - name: Run test
        run: poetry run pytest --cov=qdamakuengine
      - name: Build wheel
        run: poetry build
      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.ref_type == 'tag'
        with:
          files: dist/*
          generate_release_notes: true
